// Auto-generated. Do not edit!

// (in-package irobot_inspection_pckg.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let std_msgs = _finder('std_msgs');

//-----------------------------------------------------------

class getCompletePanoramaGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.folder_pano_path = null;
      this.images_number = null;
      this.name_0 = null;
      this.name_180 = null;
    }
    else {
      if (initObj.hasOwnProperty('folder_pano_path')) {
        this.folder_pano_path = initObj.folder_pano_path
      }
      else {
        this.folder_pano_path = new std_msgs.msg.String();
      }
      if (initObj.hasOwnProperty('images_number')) {
        this.images_number = initObj.images_number
      }
      else {
        this.images_number = 0;
      }
      if (initObj.hasOwnProperty('name_0')) {
        this.name_0 = initObj.name_0
      }
      else {
        this.name_0 = new std_msgs.msg.String();
      }
      if (initObj.hasOwnProperty('name_180')) {
        this.name_180 = initObj.name_180
      }
      else {
        this.name_180 = new std_msgs.msg.String();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type getCompletePanoramaGoal
    // Serialize message field [folder_pano_path]
    bufferOffset = std_msgs.msg.String.serialize(obj.folder_pano_path, buffer, bufferOffset);
    // Serialize message field [images_number]
    bufferOffset = _serializer.int32(obj.images_number, buffer, bufferOffset);
    // Serialize message field [name_0]
    bufferOffset = std_msgs.msg.String.serialize(obj.name_0, buffer, bufferOffset);
    // Serialize message field [name_180]
    bufferOffset = std_msgs.msg.String.serialize(obj.name_180, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type getCompletePanoramaGoal
    let len;
    let data = new getCompletePanoramaGoal(null);
    // Deserialize message field [folder_pano_path]
    data.folder_pano_path = std_msgs.msg.String.deserialize(buffer, bufferOffset);
    // Deserialize message field [images_number]
    data.images_number = _deserializer.int32(buffer, bufferOffset);
    // Deserialize message field [name_0]
    data.name_0 = std_msgs.msg.String.deserialize(buffer, bufferOffset);
    // Deserialize message field [name_180]
    data.name_180 = std_msgs.msg.String.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += std_msgs.msg.String.getMessageSize(object.folder_pano_path);
    length += std_msgs.msg.String.getMessageSize(object.name_0);
    length += std_msgs.msg.String.getMessageSize(object.name_180);
    return length + 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'irobot_inspection_pckg/getCompletePanoramaGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '2465211dc6ab145b5fd1fa5a332f2607';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #goal definition
    std_msgs/String folder_pano_path
    int32 images_number
    std_msgs/String name_0
    std_msgs/String name_180
    
    
    ================================================================================
    MSG: std_msgs/String
    string data
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new getCompletePanoramaGoal(null);
    if (msg.folder_pano_path !== undefined) {
      resolved.folder_pano_path = std_msgs.msg.String.Resolve(msg.folder_pano_path)
    }
    else {
      resolved.folder_pano_path = new std_msgs.msg.String()
    }

    if (msg.images_number !== undefined) {
      resolved.images_number = msg.images_number;
    }
    else {
      resolved.images_number = 0
    }

    if (msg.name_0 !== undefined) {
      resolved.name_0 = std_msgs.msg.String.Resolve(msg.name_0)
    }
    else {
      resolved.name_0 = new std_msgs.msg.String()
    }

    if (msg.name_180 !== undefined) {
      resolved.name_180 = std_msgs.msg.String.Resolve(msg.name_180)
    }
    else {
      resolved.name_180 = new std_msgs.msg.String()
    }

    return resolved;
    }
};

module.exports = getCompletePanoramaGoal;
