// Auto-generated. Do not edit!

// (in-package irobot_inspection_pckg.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class getImagesFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.n_imgs = null;
    }
    else {
      if (initObj.hasOwnProperty('n_imgs')) {
        this.n_imgs = initObj.n_imgs
      }
      else {
        this.n_imgs = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type getImagesFeedback
    // Serialize message field [n_imgs]
    bufferOffset = _serializer.int32(obj.n_imgs, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type getImagesFeedback
    let len;
    let data = new getImagesFeedback(null);
    // Deserialize message field [n_imgs]
    data.n_imgs = _deserializer.int32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'irobot_inspection_pckg/getImagesFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '42d742e201b01c82efbb9f90e7a251d7';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #feedback
    int32 n_imgs
    
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new getImagesFeedback(null);
    if (msg.n_imgs !== undefined) {
      resolved.n_imgs = msg.n_imgs;
    }
    else {
      resolved.n_imgs = 0
    }

    return resolved;
    }
};

module.exports = getImagesFeedback;
