// Generated by gencpp from file irobot_fcpp_simul/defecto_simple.msg
// DO NOT EDIT!


#ifndef IROBOT_FCPP_SIMUL_MESSAGE_DEFECTO_SIMPLE_H
#define IROBOT_FCPP_SIMUL_MESSAGE_DEFECTO_SIMPLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Polygon.h>

namespace irobot_fcpp_simul
{
template <class ContainerAllocator>
struct defecto_simple_
{
  typedef defecto_simple_<ContainerAllocator> Type;

  defecto_simple_()
    : ros_poly()
    , direccion_rep(0)
    , reparado(false)  {
    }
  defecto_simple_(const ContainerAllocator& _alloc)
    : ros_poly(_alloc)
    , direccion_rep(0)
    , reparado(false)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Polygon_<ContainerAllocator>  _ros_poly_type;
  _ros_poly_type ros_poly;

   typedef int32_t _direccion_rep_type;
  _direccion_rep_type direccion_rep;

   typedef uint8_t _reparado_type;
  _reparado_type reparado;





  typedef boost::shared_ptr< ::irobot_fcpp_simul::defecto_simple_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::irobot_fcpp_simul::defecto_simple_<ContainerAllocator> const> ConstPtr;

}; // struct defecto_simple_

typedef ::irobot_fcpp_simul::defecto_simple_<std::allocator<void> > defecto_simple;

typedef boost::shared_ptr< ::irobot_fcpp_simul::defecto_simple > defecto_simplePtr;
typedef boost::shared_ptr< ::irobot_fcpp_simul::defecto_simple const> defecto_simpleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::irobot_fcpp_simul::defecto_simple_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::irobot_fcpp_simul::defecto_simple_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace irobot_fcpp_simul

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg', '/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'irobot_fcpp_simul': ['/home/irobot/nav_insp_ws/src/inspection/irobot_fcpp_simul/msg', '/home/irobot/nav_insp_ws/devel/share/irobot_fcpp_simul/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::irobot_fcpp_simul::defecto_simple_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::irobot_fcpp_simul::defecto_simple_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::irobot_fcpp_simul::defecto_simple_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::irobot_fcpp_simul::defecto_simple_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::irobot_fcpp_simul::defecto_simple_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::irobot_fcpp_simul::defecto_simple_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::irobot_fcpp_simul::defecto_simple_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9e9103e825e653e77fe6292f6a6f8a76";
  }

  static const char* value(const ::irobot_fcpp_simul::defecto_simple_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9e9103e825e653e7ULL;
  static const uint64_t static_value2 = 0x7fe6292f6a6f8a76ULL;
};

template<class ContainerAllocator>
struct DataType< ::irobot_fcpp_simul::defecto_simple_<ContainerAllocator> >
{
  static const char* value()
  {
    return "irobot_fcpp_simul/defecto_simple";
  }

  static const char* value(const ::irobot_fcpp_simul::defecto_simple_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::irobot_fcpp_simul::defecto_simple_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Polygon ros_poly\n\
int32 direccion_rep\n\
bool reparado\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Polygon\n\
#A specification of a polygon where the first and last points are assumed to be connected\n\
Point32[] points\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point32\n\
# This contains the position of a point in free space(with 32 bits of precision).\n\
# It is recommeded to use Point wherever possible instead of Point32.  \n\
# \n\
# This recommendation is to promote interoperability.  \n\
#\n\
# This message is designed to take up less space when sending\n\
# lots of points at once, as in the case of a PointCloud.  \n\
\n\
float32 x\n\
float32 y\n\
float32 z\n\
";
  }

  static const char* value(const ::irobot_fcpp_simul::defecto_simple_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::irobot_fcpp_simul::defecto_simple_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ros_poly);
      stream.next(m.direccion_rep);
      stream.next(m.reparado);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct defecto_simple_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::irobot_fcpp_simul::defecto_simple_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::irobot_fcpp_simul::defecto_simple_<ContainerAllocator>& v)
  {
    s << indent << "ros_poly: ";
    s << std::endl;
    Printer< ::geometry_msgs::Polygon_<ContainerAllocator> >::stream(s, indent + "  ", v.ros_poly);
    s << indent << "direccion_rep: ";
    Printer<int32_t>::stream(s, indent + "  ", v.direccion_rep);
    s << indent << "reparado: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.reparado);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IROBOT_FCPP_SIMUL_MESSAGE_DEFECTO_SIMPLE_H
