// Generated by gencpp from file action_server_package/BaseRotationFeedback.msg
// DO NOT EDIT!


#ifndef ACTION_SERVER_PACKAGE_MESSAGE_BASEROTATIONFEEDBACK_H
#define ACTION_SERVER_PACKAGE_MESSAGE_BASEROTATIONFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace action_server_package
{
template <class ContainerAllocator>
struct BaseRotationFeedback_
{
  typedef BaseRotationFeedback_<ContainerAllocator> Type;

  BaseRotationFeedback_()
    : degrees_rotated(0.0)  {
    }
  BaseRotationFeedback_(const ContainerAllocator& _alloc)
    : degrees_rotated(0.0)  {
  (void)_alloc;
    }



   typedef float _degrees_rotated_type;
  _degrees_rotated_type degrees_rotated;





  typedef boost::shared_ptr< ::action_server_package::BaseRotationFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::action_server_package::BaseRotationFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct BaseRotationFeedback_

typedef ::action_server_package::BaseRotationFeedback_<std::allocator<void> > BaseRotationFeedback;

typedef boost::shared_ptr< ::action_server_package::BaseRotationFeedback > BaseRotationFeedbackPtr;
typedef boost::shared_ptr< ::action_server_package::BaseRotationFeedback const> BaseRotationFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::action_server_package::BaseRotationFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::action_server_package::BaseRotationFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace action_server_package

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'action_server_package': ['/home/irobot/nav_insp_ws/devel/share/action_server_package/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::action_server_package::BaseRotationFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::action_server_package::BaseRotationFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::action_server_package::BaseRotationFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::action_server_package::BaseRotationFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action_server_package::BaseRotationFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action_server_package::BaseRotationFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::action_server_package::BaseRotationFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c040fa1e4a8dbeca4b61397439ea933d";
  }

  static const char* value(const ::action_server_package::BaseRotationFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc040fa1e4a8dbecaULL;
  static const uint64_t static_value2 = 0x4b61397439ea933dULL;
};

template<class ContainerAllocator>
struct DataType< ::action_server_package::BaseRotationFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "action_server_package/BaseRotationFeedback";
  }

  static const char* value(const ::action_server_package::BaseRotationFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::action_server_package::BaseRotationFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define a feedback message\n\
float32 degrees_rotated\n\
";
  }

  static const char* value(const ::action_server_package::BaseRotationFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::action_server_package::BaseRotationFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.degrees_rotated);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BaseRotationFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::action_server_package::BaseRotationFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::action_server_package::BaseRotationFeedback_<ContainerAllocator>& v)
  {
    s << indent << "degrees_rotated: ";
    Printer<float>::stream(s, indent + "  ", v.degrees_rotated);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACTION_SERVER_PACKAGE_MESSAGE_BASEROTATIONFEEDBACK_H
