// Generated by gencpp from file action_server_package/ChapaStorage.msg
// DO NOT EDIT!


#ifndef ACTION_SERVER_PACKAGE_MESSAGE_CHAPASTORAGE_H
#define ACTION_SERVER_PACKAGE_MESSAGE_CHAPASTORAGE_H

#include <ros/service_traits.h>


#include <action_server_package/ChapaStorageRequest.h>
#include <action_server_package/ChapaStorageResponse.h>


namespace action_server_package
{

struct ChapaStorage
{

typedef ChapaStorageRequest Request;
typedef ChapaStorageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ChapaStorage
} // namespace action_server_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::action_server_package::ChapaStorage > {
  static const char* value()
  {
    return "d420ea154534426ff59c21556a0bdbf4";
  }

  static const char* value(const ::action_server_package::ChapaStorage&) { return value(); }
};

template<>
struct DataType< ::action_server_package::ChapaStorage > {
  static const char* value()
  {
    return "action_server_package/ChapaStorage";
  }

  static const char* value(const ::action_server_package::ChapaStorage&) { return value(); }
};


// service_traits::MD5Sum< ::action_server_package::ChapaStorageRequest> should match 
// service_traits::MD5Sum< ::action_server_package::ChapaStorage > 
template<>
struct MD5Sum< ::action_server_package::ChapaStorageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::action_server_package::ChapaStorage >::value();
  }
  static const char* value(const ::action_server_package::ChapaStorageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::action_server_package::ChapaStorageRequest> should match 
// service_traits::DataType< ::action_server_package::ChapaStorage > 
template<>
struct DataType< ::action_server_package::ChapaStorageRequest>
{
  static const char* value()
  {
    return DataType< ::action_server_package::ChapaStorage >::value();
  }
  static const char* value(const ::action_server_package::ChapaStorageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::action_server_package::ChapaStorageResponse> should match 
// service_traits::MD5Sum< ::action_server_package::ChapaStorage > 
template<>
struct MD5Sum< ::action_server_package::ChapaStorageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::action_server_package::ChapaStorage >::value();
  }
  static const char* value(const ::action_server_package::ChapaStorageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::action_server_package::ChapaStorageResponse> should match 
// service_traits::DataType< ::action_server_package::ChapaStorage > 
template<>
struct DataType< ::action_server_package::ChapaStorageResponse>
{
  static const char* value()
  {
    return DataType< ::action_server_package::ChapaStorage >::value();
  }
  static const char* value(const ::action_server_package::ChapaStorageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ACTION_SERVER_PACKAGE_MESSAGE_CHAPASTORAGE_H
