; Auto-generated. Do not edit!


(cl:in-package action_server_package-msg)


;//! \htmlinclude BaseRotationResult.msg.html

(cl:defclass <BaseRotationResult> (roslisp-msg-protocol:ros-message)
  ((final_yaw
    :reader final_yaw
    :initarg :final_yaw
    :type cl:float
    :initform 0.0))
)

(cl:defclass BaseRotationResult (<BaseRotationResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <BaseRotationResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'BaseRotationResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name action_server_package-msg:<BaseRotationResult> is deprecated: use action_server_package-msg:BaseRotationResult instead.")))

(cl:ensure-generic-function 'final_yaw-val :lambda-list '(m))
(cl:defmethod final_yaw-val ((m <BaseRotationResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader action_server_package-msg:final_yaw-val is deprecated.  Use action_server_package-msg:final_yaw instead.")
  (final_yaw m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <BaseRotationResult>) ostream)
  "Serializes a message object of type '<BaseRotationResult>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'final_yaw))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <BaseRotationResult>) istream)
  "Deserializes a message object of type '<BaseRotationResult>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'final_yaw) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<BaseRotationResult>)))
  "Returns string type for a message object of type '<BaseRotationResult>"
  "action_server_package/BaseRotationResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'BaseRotationResult)))
  "Returns string type for a message object of type 'BaseRotationResult"
  "action_server_package/BaseRotationResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<BaseRotationResult>)))
  "Returns md5sum for a message object of type '<BaseRotationResult>"
  "d43731d6fbe32b7ac8cb4548c278fc73")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'BaseRotationResult)))
  "Returns md5sum for a message object of type 'BaseRotationResult"
  "d43731d6fbe32b7ac8cb4548c278fc73")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<BaseRotationResult>)))
  "Returns full string definition for message of type '<BaseRotationResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%float32 final_yaw~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'BaseRotationResult)))
  "Returns full string definition for message of type 'BaseRotationResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%float32 final_yaw~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <BaseRotationResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <BaseRotationResult>))
  "Converts a ROS message object to a list"
  (cl:list 'BaseRotationResult
    (cl:cons ':final_yaw (final_yaw msg))
))
