; Auto-generated. Do not edit!


(cl:in-package irobot_fcpp_simul-msg)


;//! \htmlinclude ExecutePathFeedback.msg.html

(cl:defclass <ExecutePathFeedback> (roslisp-msg-protocol:ros-message)
  ((recorrido
    :reader recorrido
    :initarg :recorrido
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass ExecutePathFeedback (<ExecutePathFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ExecutePathFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ExecutePathFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name irobot_fcpp_simul-msg:<ExecutePathFeedback> is deprecated: use irobot_fcpp_simul-msg:ExecutePathFeedback instead.")))

(cl:ensure-generic-function 'recorrido-val :lambda-list '(m))
(cl:defmethod recorrido-val ((m <ExecutePathFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader irobot_fcpp_simul-msg:recorrido-val is deprecated.  Use irobot_fcpp_simul-msg:recorrido instead.")
  (recorrido m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ExecutePathFeedback>) ostream)
  "Serializes a message object of type '<ExecutePathFeedback>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'recorrido) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ExecutePathFeedback>) istream)
  "Deserializes a message object of type '<ExecutePathFeedback>"
    (cl:setf (cl:slot-value msg 'recorrido) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ExecutePathFeedback>)))
  "Returns string type for a message object of type '<ExecutePathFeedback>"
  "irobot_fcpp_simul/ExecutePathFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ExecutePathFeedback)))
  "Returns string type for a message object of type 'ExecutePathFeedback"
  "irobot_fcpp_simul/ExecutePathFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ExecutePathFeedback>)))
  "Returns md5sum for a message object of type '<ExecutePathFeedback>"
  "ca38ebdc9ec96d5ed4262d9bf2765883")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ExecutePathFeedback)))
  "Returns md5sum for a message object of type 'ExecutePathFeedback"
  "ca38ebdc9ec96d5ed4262d9bf2765883")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ExecutePathFeedback>)))
  "Returns full string definition for message of type '<ExecutePathFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%bool recorrido~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ExecutePathFeedback)))
  "Returns full string definition for message of type 'ExecutePathFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%bool recorrido~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ExecutePathFeedback>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ExecutePathFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ExecutePathFeedback
    (cl:cons ':recorrido (recorrido msg))
))
