(cl:in-package irobot_fcpp_simul-srv)
(cl:export '(ID_INPUT-VAL
          ID_INPUT
          GET_WORKING_ZONES-VAL
          GET_WORKING_ZONES
          GET_INSPECTION_ZONES-VAL
          GET_INSPECTION_ZONES
          GET_ROT_ZONE-VAL
          GET_ROT_ZONE
          N_DEFECTS-VAL
          N_DEFECTS
          HERR_LAT-VAL
          HERR_LAT
          HERR_PROA-VAL
          HERR_PROA
          HERR_POPA-VAL
          HERR_POPA
          LONG_ROBOTX-VAL
          LONG_ROBOTX
          LONG_ROBOTY-VAL
          LONG_ROBOTY
          TRAS_HERRX-VAL
          TRAS_HERRX
          TRAS_HERRY-VAL
          TRAS_HERRY
          XMIN_CHAPA-VAL
          XMIN_CHAPA
          XMAX_CHAPA-VAL
          XMAX_CHAPA
          YMIN_CHAPA-VAL
          YMIN_CHAPA
          YMAX_CHAPA-VAL
          YMAX_CHAPA
          POLY_I-VAL
          POLY_I
          ZONE0-VAL
          ZONE0
          ZONE90-VAL
          ZONE90
          ZONE180-VAL
          ZONE180
          ZONE270-VAL
          ZONE270
          ZONE_ROT-VAL
          ZONE_ROT
))