; Auto-generated. Do not edit!


(cl:in-package irobot_inspection_pckg-msg)


;//! \htmlinclude getImagesResult.msg.html

(cl:defclass <getImagesResult> (roslisp-msg-protocol:ros-message)
  ((finished
    :reader finished
    :initarg :finished
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass getImagesResult (<getImagesResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <getImagesResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'getImagesResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name irobot_inspection_pckg-msg:<getImagesResult> is deprecated: use irobot_inspection_pckg-msg:getImagesResult instead.")))

(cl:ensure-generic-function 'finished-val :lambda-list '(m))
(cl:defmethod finished-val ((m <getImagesResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader irobot_inspection_pckg-msg:finished-val is deprecated.  Use irobot_inspection_pckg-msg:finished instead.")
  (finished m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <getImagesResult>) ostream)
  "Serializes a message object of type '<getImagesResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'finished) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <getImagesResult>) istream)
  "Deserializes a message object of type '<getImagesResult>"
    (cl:setf (cl:slot-value msg 'finished) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<getImagesResult>)))
  "Returns string type for a message object of type '<getImagesResult>"
  "irobot_inspection_pckg/getImagesResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'getImagesResult)))
  "Returns string type for a message object of type 'getImagesResult"
  "irobot_inspection_pckg/getImagesResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<getImagesResult>)))
  "Returns md5sum for a message object of type '<getImagesResult>"
  "e2797c797e620a950ba704492d72873b")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'getImagesResult)))
  "Returns md5sum for a message object of type 'getImagesResult"
  "e2797c797e620a950ba704492d72873b")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<getImagesResult>)))
  "Returns full string definition for message of type '<getImagesResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%bool finished~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'getImagesResult)))
  "Returns full string definition for message of type 'getImagesResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%bool finished~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <getImagesResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <getImagesResult>))
  "Converts a ROS message object to a list"
  (cl:list 'getImagesResult
    (cl:cons ':finished (finished msg))
))
