
(cl:in-package :asdf)

(defsystem "action_server_package-msg"
  :depends-on (:roslisp-msg-protocol :roslisp-utils :actionlib_msgs-msg
               :geometry_msgs-msg
               :std_msgs-msg
)
  :components ((:file "_package")
    (:file "BaseRotationAction" :depends-on ("_package_BaseRotationAction"))
    (:file "_package_BaseRotationAction" :depends-on ("_package"))
    (:file "BaseRotationActionFeedback" :depends-on ("_package_BaseRotationActionFeedback"))
    (:file "_package_BaseRotationActionFeedback" :depends-on ("_package"))
    (:file "BaseRotationActionGoal" :depends-on ("_package_BaseRotationActionGoal"))
    (:file "_package_BaseRotationActionGoal" :depends-on ("_package"))
    (:file "BaseRotationActionResult" :depends-on ("_package_BaseRotationActionResult"))
    (:file "_package_BaseRotationActionResult" :depends-on ("_package"))
    (:file "BaseRotationFeedback" :depends-on ("_package_BaseRotationFeedback"))
    (:file "_package_BaseRotationFeedback" :depends-on ("_package"))
    (:file "BaseRotationGoal" :depends-on ("_package_BaseRotationGoal"))
    (:file "_package_BaseRotationGoal" :depends-on ("_package"))
    (:file "BaseRotationResult" :depends-on ("_package_BaseRotationResult"))
    (:file "_package_BaseRotationResult" :depends-on ("_package"))
    (:file "CompleteRectangleCoverageAction" :depends-on ("_package_CompleteRectangleCoverageAction"))
    (:file "_package_CompleteRectangleCoverageAction" :depends-on ("_package"))
    (:file "CompleteRectangleCoverageActionFeedback" :depends-on ("_package_CompleteRectangleCoverageActionFeedback"))
    (:file "_package_CompleteRectangleCoverageActionFeedback" :depends-on ("_package"))
    (:file "CompleteRectangleCoverageActionGoal" :depends-on ("_package_CompleteRectangleCoverageActionGoal"))
    (:file "_package_CompleteRectangleCoverageActionGoal" :depends-on ("_package"))
    (:file "CompleteRectangleCoverageActionResult" :depends-on ("_package_CompleteRectangleCoverageActionResult"))
    (:file "_package_CompleteRectangleCoverageActionResult" :depends-on ("_package"))
    (:file "CompleteRectangleCoverageFeedback" :depends-on ("_package_CompleteRectangleCoverageFeedback"))
    (:file "_package_CompleteRectangleCoverageFeedback" :depends-on ("_package"))
    (:file "CompleteRectangleCoverageGoal" :depends-on ("_package_CompleteRectangleCoverageGoal"))
    (:file "_package_CompleteRectangleCoverageGoal" :depends-on ("_package"))
    (:file "CompleteRectangleCoverageResult" :depends-on ("_package_CompleteRectangleCoverageResult"))
    (:file "_package_CompleteRectangleCoverageResult" :depends-on ("_package"))
    (:file "MoveRobotCoordAction" :depends-on ("_package_MoveRobotCoordAction"))
    (:file "_package_MoveRobotCoordAction" :depends-on ("_package"))
    (:file "MoveRobotCoordActionFeedback" :depends-on ("_package_MoveRobotCoordActionFeedback"))
    (:file "_package_MoveRobotCoordActionFeedback" :depends-on ("_package"))
    (:file "MoveRobotCoordActionGoal" :depends-on ("_package_MoveRobotCoordActionGoal"))
    (:file "_package_MoveRobotCoordActionGoal" :depends-on ("_package"))
    (:file "MoveRobotCoordActionResult" :depends-on ("_package_MoveRobotCoordActionResult"))
    (:file "_package_MoveRobotCoordActionResult" :depends-on ("_package"))
    (:file "MoveRobotCoordFeedback" :depends-on ("_package_MoveRobotCoordFeedback"))
    (:file "_package_MoveRobotCoordFeedback" :depends-on ("_package"))
    (:file "MoveRobotCoordGoal" :depends-on ("_package_MoveRobotCoordGoal"))
    (:file "_package_MoveRobotCoordGoal" :depends-on ("_package"))
    (:file "MoveRobotCoordResult" :depends-on ("_package_MoveRobotCoordResult"))
    (:file "_package_MoveRobotCoordResult" :depends-on ("_package"))
    (:file "RectangleCoveragePathPlanningAction" :depends-on ("_package_RectangleCoveragePathPlanningAction"))
    (:file "_package_RectangleCoveragePathPlanningAction" :depends-on ("_package"))
    (:file "RectangleCoveragePathPlanningActionFeedback" :depends-on ("_package_RectangleCoveragePathPlanningActionFeedback"))
    (:file "_package_RectangleCoveragePathPlanningActionFeedback" :depends-on ("_package"))
    (:file "RectangleCoveragePathPlanningActionGoal" :depends-on ("_package_RectangleCoveragePathPlanningActionGoal"))
    (:file "_package_RectangleCoveragePathPlanningActionGoal" :depends-on ("_package"))
    (:file "RectangleCoveragePathPlanningActionResult" :depends-on ("_package_RectangleCoveragePathPlanningActionResult"))
    (:file "_package_RectangleCoveragePathPlanningActionResult" :depends-on ("_package"))
    (:file "RectangleCoveragePathPlanningFeedback" :depends-on ("_package_RectangleCoveragePathPlanningFeedback"))
    (:file "_package_RectangleCoveragePathPlanningFeedback" :depends-on ("_package"))
    (:file "RectangleCoveragePathPlanningGoal" :depends-on ("_package_RectangleCoveragePathPlanningGoal"))
    (:file "_package_RectangleCoveragePathPlanningGoal" :depends-on ("_package"))
    (:file "RectangleCoveragePathPlanningResult" :depends-on ("_package_RectangleCoveragePathPlanningResult"))
    (:file "_package_RectangleCoveragePathPlanningResult" :depends-on ("_package"))
  ))