// Generated by gencpp from file action_server_package/FCPP_in.msg
// DO NOT EDIT!


#ifndef ACTION_SERVER_PACKAGE_MESSAGE_FCPP_IN_H
#define ACTION_SERVER_PACKAGE_MESSAGE_FCPP_IN_H

#include <ros/service_traits.h>


#include <action_server_package/FCPP_inRequest.h>
#include <action_server_package/FCPP_inResponse.h>


namespace action_server_package
{

struct FCPP_in
{

typedef FCPP_inRequest Request;
typedef FCPP_inResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FCPP_in
} // namespace action_server_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::action_server_package::FCPP_in > {
  static const char* value()
  {
    return "3a9946ec5195dc8fb4f14eeb6ec2e339";
  }

  static const char* value(const ::action_server_package::FCPP_in&) { return value(); }
};

template<>
struct DataType< ::action_server_package::FCPP_in > {
  static const char* value()
  {
    return "action_server_package/FCPP_in";
  }

  static const char* value(const ::action_server_package::FCPP_in&) { return value(); }
};


// service_traits::MD5Sum< ::action_server_package::FCPP_inRequest> should match 
// service_traits::MD5Sum< ::action_server_package::FCPP_in > 
template<>
struct MD5Sum< ::action_server_package::FCPP_inRequest>
{
  static const char* value()
  {
    return MD5Sum< ::action_server_package::FCPP_in >::value();
  }
  static const char* value(const ::action_server_package::FCPP_inRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::action_server_package::FCPP_inRequest> should match 
// service_traits::DataType< ::action_server_package::FCPP_in > 
template<>
struct DataType< ::action_server_package::FCPP_inRequest>
{
  static const char* value()
  {
    return DataType< ::action_server_package::FCPP_in >::value();
  }
  static const char* value(const ::action_server_package::FCPP_inRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::action_server_package::FCPP_inResponse> should match 
// service_traits::MD5Sum< ::action_server_package::FCPP_in > 
template<>
struct MD5Sum< ::action_server_package::FCPP_inResponse>
{
  static const char* value()
  {
    return MD5Sum< ::action_server_package::FCPP_in >::value();
  }
  static const char* value(const ::action_server_package::FCPP_inResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::action_server_package::FCPP_inResponse> should match 
// service_traits::DataType< ::action_server_package::FCPP_in > 
template<>
struct DataType< ::action_server_package::FCPP_inResponse>
{
  static const char* value()
  {
    return DataType< ::action_server_package::FCPP_in >::value();
  }
  static const char* value(const ::action_server_package::FCPP_inResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ACTION_SERVER_PACKAGE_MESSAGE_FCPP_IN_H
