# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from irobot_dimensions_pckg/obtainDimensionGoal.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class obtainDimensionGoal(genpy.Message):
  _md5sum = "d5a4c79a4840d0e4c90009d8806c0768"
  _type = "irobot_dimensions_pckg/obtainDimensionGoal"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
#goal definition
std_msgs/String folder_path1
int32 n_imgs1
std_msgs/String folder_path2
int32 n_imgs2

================================================================================
MSG: std_msgs/String
string data
"""
  __slots__ = ['folder_path1','n_imgs1','folder_path2','n_imgs2']
  _slot_types = ['std_msgs/String','int32','std_msgs/String','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       folder_path1,n_imgs1,folder_path2,n_imgs2

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(obtainDimensionGoal, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.folder_path1 is None:
        self.folder_path1 = std_msgs.msg.String()
      if self.n_imgs1 is None:
        self.n_imgs1 = 0
      if self.folder_path2 is None:
        self.folder_path2 = std_msgs.msg.String()
      if self.n_imgs2 is None:
        self.n_imgs2 = 0
    else:
      self.folder_path1 = std_msgs.msg.String()
      self.n_imgs1 = 0
      self.folder_path2 = std_msgs.msg.String()
      self.n_imgs2 = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.folder_path1.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.n_imgs1
      buff.write(_get_struct_i().pack(_x))
      _x = self.folder_path2.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.n_imgs2
      buff.write(_get_struct_i().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.folder_path1 is None:
        self.folder_path1 = std_msgs.msg.String()
      if self.folder_path2 is None:
        self.folder_path2 = std_msgs.msg.String()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.folder_path1.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.folder_path1.data = str[start:end]
      start = end
      end += 4
      (self.n_imgs1,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.folder_path2.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.folder_path2.data = str[start:end]
      start = end
      end += 4
      (self.n_imgs2,) = _get_struct_i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.folder_path1.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.n_imgs1
      buff.write(_get_struct_i().pack(_x))
      _x = self.folder_path2.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.n_imgs2
      buff.write(_get_struct_i().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.folder_path1 is None:
        self.folder_path1 = std_msgs.msg.String()
      if self.folder_path2 is None:
        self.folder_path2 = std_msgs.msg.String()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.folder_path1.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.folder_path1.data = str[start:end]
      start = end
      end += 4
      (self.n_imgs1,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.folder_path2.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.folder_path2.data = str[start:end]
      start = end
      end += 4
      (self.n_imgs2,) = _get_struct_i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_i = None
def _get_struct_i():
    global _struct_i
    if _struct_i is None:
        _struct_i = struct.Struct("<i")
    return _struct_i
