; Auto-generated. Do not edit!


(cl:in-package inspection_realsense-msg)


;//! \htmlinclude captureImagesGoal.msg.html

(cl:defclass <captureImagesGoal> (roslisp-msg-protocol:ros-message)
  ((folder_path
    :reader folder_path
    :initarg :folder_path
    :type std_msgs-msg:String
    :initform (cl:make-instance 'std_msgs-msg:String)))
)

(cl:defclass captureImagesGoal (<captureImagesGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <captureImagesGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'captureImagesGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name inspection_realsense-msg:<captureImagesGoal> is deprecated: use inspection_realsense-msg:captureImagesGoal instead.")))

(cl:ensure-generic-function 'folder_path-val :lambda-list '(m))
(cl:defmethod folder_path-val ((m <captureImagesGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader inspection_realsense-msg:folder_path-val is deprecated.  Use inspection_realsense-msg:folder_path instead.")
  (folder_path m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <captureImagesGoal>) ostream)
  "Serializes a message object of type '<captureImagesGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'folder_path) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <captureImagesGoal>) istream)
  "Deserializes a message object of type '<captureImagesGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'folder_path) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<captureImagesGoal>)))
  "Returns string type for a message object of type '<captureImagesGoal>"
  "inspection_realsense/captureImagesGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'captureImagesGoal)))
  "Returns string type for a message object of type 'captureImagesGoal"
  "inspection_realsense/captureImagesGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<captureImagesGoal>)))
  "Returns md5sum for a message object of type '<captureImagesGoal>"
  "7e3638c220b0d90e6c19901c22f34e46")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'captureImagesGoal)))
  "Returns md5sum for a message object of type 'captureImagesGoal"
  "7e3638c220b0d90e6c19901c22f34e46")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<captureImagesGoal>)))
  "Returns full string definition for message of type '<captureImagesGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%std_msgs/String folder_path~%~%================================================================================~%MSG: std_msgs/String~%string data~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'captureImagesGoal)))
  "Returns full string definition for message of type 'captureImagesGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%std_msgs/String folder_path~%~%================================================================================~%MSG: std_msgs/String~%string data~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <captureImagesGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'folder_path))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <captureImagesGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'captureImagesGoal
    (cl:cons ':folder_path (folder_path msg))
))
