; Auto-generated. Do not edit!


(cl:in-package inspection_realsense-msg)


;//! \htmlinclude findInitialPoseResult.msg.html

(cl:defclass <findInitialPoseResult> (roslisp-msg-protocol:ros-message)
  ((finished
    :reader finished
    :initarg :finished
    :type cl:boolean
    :initform cl:nil)
   (n_pasadas_totales
    :reader n_pasadas_totales
    :initarg :n_pasadas_totales
    :type cl:integer
    :initform 0))
)

(cl:defclass findInitialPoseResult (<findInitialPoseResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <findInitialPoseResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'findInitialPoseResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name inspection_realsense-msg:<findInitialPoseResult> is deprecated: use inspection_realsense-msg:findInitialPoseResult instead.")))

(cl:ensure-generic-function 'finished-val :lambda-list '(m))
(cl:defmethod finished-val ((m <findInitialPoseResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader inspection_realsense-msg:finished-val is deprecated.  Use inspection_realsense-msg:finished instead.")
  (finished m))

(cl:ensure-generic-function 'n_pasadas_totales-val :lambda-list '(m))
(cl:defmethod n_pasadas_totales-val ((m <findInitialPoseResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader inspection_realsense-msg:n_pasadas_totales-val is deprecated.  Use inspection_realsense-msg:n_pasadas_totales instead.")
  (n_pasadas_totales m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <findInitialPoseResult>) ostream)
  "Serializes a message object of type '<findInitialPoseResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'finished) 1 0)) ostream)
  (cl:let* ((signed (cl:slot-value msg 'n_pasadas_totales)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <findInitialPoseResult>) istream)
  "Deserializes a message object of type '<findInitialPoseResult>"
    (cl:setf (cl:slot-value msg 'finished) (cl:not (cl:zerop (cl:read-byte istream))))
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'n_pasadas_totales) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<findInitialPoseResult>)))
  "Returns string type for a message object of type '<findInitialPoseResult>"
  "inspection_realsense/findInitialPoseResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'findInitialPoseResult)))
  "Returns string type for a message object of type 'findInitialPoseResult"
  "inspection_realsense/findInitialPoseResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<findInitialPoseResult>)))
  "Returns md5sum for a message object of type '<findInitialPoseResult>"
  "0364f8fadbc00287ab44396c35cc11f8")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'findInitialPoseResult)))
  "Returns md5sum for a message object of type 'findInitialPoseResult"
  "0364f8fadbc00287ab44396c35cc11f8")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<findInitialPoseResult>)))
  "Returns full string definition for message of type '<findInitialPoseResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%bool finished~%int32 n_pasadas_totales~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'findInitialPoseResult)))
  "Returns full string definition for message of type 'findInitialPoseResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%bool finished~%int32 n_pasadas_totales~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <findInitialPoseResult>))
  (cl:+ 0
     1
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <findInitialPoseResult>))
  "Converts a ROS message object to a list"
  (cl:list 'findInitialPoseResult
    (cl:cons ':finished (finished msg))
    (cl:cons ':n_pasadas_totales (n_pasadas_totales msg))
))
