; Auto-generated. Do not edit!


(cl:in-package inspection_realsense-msg)


;//! \htmlinclude moveLeftStepResult.msg.html

(cl:defclass <moveLeftStepResult> (roslisp-msg-protocol:ros-message)
  ((finished
    :reader finished
    :initarg :finished
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass moveLeftStepResult (<moveLeftStepResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <moveLeftStepResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'moveLeftStepResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name inspection_realsense-msg:<moveLeftStepResult> is deprecated: use inspection_realsense-msg:moveLeftStepResult instead.")))

(cl:ensure-generic-function 'finished-val :lambda-list '(m))
(cl:defmethod finished-val ((m <moveLeftStepResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader inspection_realsense-msg:finished-val is deprecated.  Use inspection_realsense-msg:finished instead.")
  (finished m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <moveLeftStepResult>) ostream)
  "Serializes a message object of type '<moveLeftStepResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'finished) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <moveLeftStepResult>) istream)
  "Deserializes a message object of type '<moveLeftStepResult>"
    (cl:setf (cl:slot-value msg 'finished) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<moveLeftStepResult>)))
  "Returns string type for a message object of type '<moveLeftStepResult>"
  "inspection_realsense/moveLeftStepResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'moveLeftStepResult)))
  "Returns string type for a message object of type 'moveLeftStepResult"
  "inspection_realsense/moveLeftStepResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<moveLeftStepResult>)))
  "Returns md5sum for a message object of type '<moveLeftStepResult>"
  "e2797c797e620a950ba704492d72873b")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'moveLeftStepResult)))
  "Returns md5sum for a message object of type 'moveLeftStepResult"
  "e2797c797e620a950ba704492d72873b")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<moveLeftStepResult>)))
  "Returns full string definition for message of type '<moveLeftStepResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%bool finished~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'moveLeftStepResult)))
  "Returns full string definition for message of type 'moveLeftStepResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%bool finished~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <moveLeftStepResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <moveLeftStepResult>))
  "Converts a ROS message object to a list"
  (cl:list 'moveLeftStepResult
    (cl:cons ':finished (finished msg))
))
