// Generated by gencpp from file aux_controllers/SetFrame.msg
// DO NOT EDIT!


#ifndef AUX_CONTROLLERS_MESSAGE_SETFRAME_H
#define AUX_CONTROLLERS_MESSAGE_SETFRAME_H

#include <ros/service_traits.h>


#include <aux_controllers/SetFrameRequest.h>
#include <aux_controllers/SetFrameResponse.h>


namespace aux_controllers
{

struct SetFrame
{

typedef SetFrameRequest Request;
typedef SetFrameResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetFrame
} // namespace aux_controllers


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::aux_controllers::SetFrame > {
  static const char* value()
  {
    return "fc7b3836a679f38a5c6b9328b643f1e8";
  }

  static const char* value(const ::aux_controllers::SetFrame&) { return value(); }
};

template<>
struct DataType< ::aux_controllers::SetFrame > {
  static const char* value()
  {
    return "aux_controllers/SetFrame";
  }

  static const char* value(const ::aux_controllers::SetFrame&) { return value(); }
};


// service_traits::MD5Sum< ::aux_controllers::SetFrameRequest> should match 
// service_traits::MD5Sum< ::aux_controllers::SetFrame > 
template<>
struct MD5Sum< ::aux_controllers::SetFrameRequest>
{
  static const char* value()
  {
    return MD5Sum< ::aux_controllers::SetFrame >::value();
  }
  static const char* value(const ::aux_controllers::SetFrameRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::aux_controllers::SetFrameRequest> should match 
// service_traits::DataType< ::aux_controllers::SetFrame > 
template<>
struct DataType< ::aux_controllers::SetFrameRequest>
{
  static const char* value()
  {
    return DataType< ::aux_controllers::SetFrame >::value();
  }
  static const char* value(const ::aux_controllers::SetFrameRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::aux_controllers::SetFrameResponse> should match 
// service_traits::MD5Sum< ::aux_controllers::SetFrame > 
template<>
struct MD5Sum< ::aux_controllers::SetFrameResponse>
{
  static const char* value()
  {
    return MD5Sum< ::aux_controllers::SetFrame >::value();
  }
  static const char* value(const ::aux_controllers::SetFrameResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::aux_controllers::SetFrameResponse> should match 
// service_traits::DataType< ::aux_controllers::SetFrame > 
template<>
struct DataType< ::aux_controllers::SetFrameResponse>
{
  static const char* value()
  {
    return DataType< ::aux_controllers::SetFrame >::value();
  }
  static const char* value(const ::aux_controllers::SetFrameResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AUX_CONTROLLERS_MESSAGE_SETFRAME_H
