// Generated by gencpp from file inspection_realsense/checkNewScanBackwardResult.msg
// DO NOT EDIT!


#ifndef INSPECTION_REALSENSE_MESSAGE_CHECKNEWSCANBACKWARDRESULT_H
#define INSPECTION_REALSENSE_MESSAGE_CHECKNEWSCANBACKWARDRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace inspection_realsense
{
template <class ContainerAllocator>
struct checkNewScanBackwardResult_
{
  typedef checkNewScanBackwardResult_<ContainerAllocator> Type;

  checkNewScanBackwardResult_()
    : finished(false)
    , newScanIsNeeded(false)  {
    }
  checkNewScanBackwardResult_(const ContainerAllocator& _alloc)
    : finished(false)
    , newScanIsNeeded(false)  {
  (void)_alloc;
    }



   typedef uint8_t _finished_type;
  _finished_type finished;

   typedef uint8_t _newScanIsNeeded_type;
  _newScanIsNeeded_type newScanIsNeeded;





  typedef boost::shared_ptr< ::inspection_realsense::checkNewScanBackwardResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::inspection_realsense::checkNewScanBackwardResult_<ContainerAllocator> const> ConstPtr;

}; // struct checkNewScanBackwardResult_

typedef ::inspection_realsense::checkNewScanBackwardResult_<std::allocator<void> > checkNewScanBackwardResult;

typedef boost::shared_ptr< ::inspection_realsense::checkNewScanBackwardResult > checkNewScanBackwardResultPtr;
typedef boost::shared_ptr< ::inspection_realsense::checkNewScanBackwardResult const> checkNewScanBackwardResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::inspection_realsense::checkNewScanBackwardResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::inspection_realsense::checkNewScanBackwardResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace inspection_realsense

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'inspection_realsense': ['/home/irobot/nav_insp_ws/devel/share/inspection_realsense/msg', '/home/irobot/nav_insp_ws/src/inspection_realsense/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::inspection_realsense::checkNewScanBackwardResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::inspection_realsense::checkNewScanBackwardResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::inspection_realsense::checkNewScanBackwardResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::inspection_realsense::checkNewScanBackwardResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::inspection_realsense::checkNewScanBackwardResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::inspection_realsense::checkNewScanBackwardResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::inspection_realsense::checkNewScanBackwardResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "188fa3a6dc495263b9b41941f1b7ee85";
  }

  static const char* value(const ::inspection_realsense::checkNewScanBackwardResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x188fa3a6dc495263ULL;
  static const uint64_t static_value2 = 0xb9b41941f1b7ee85ULL;
};

template<class ContainerAllocator>
struct DataType< ::inspection_realsense::checkNewScanBackwardResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "inspection_realsense/checkNewScanBackwardResult";
  }

  static const char* value(const ::inspection_realsense::checkNewScanBackwardResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::inspection_realsense::checkNewScanBackwardResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#result definition\n\
bool finished\n\
bool newScanIsNeeded\n\
";
  }

  static const char* value(const ::inspection_realsense::checkNewScanBackwardResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::inspection_realsense::checkNewScanBackwardResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.finished);
      stream.next(m.newScanIsNeeded);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct checkNewScanBackwardResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::inspection_realsense::checkNewScanBackwardResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::inspection_realsense::checkNewScanBackwardResult_<ContainerAllocator>& v)
  {
    s << indent << "finished: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.finished);
    s << indent << "newScanIsNeeded: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.newScanIsNeeded);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INSPECTION_REALSENSE_MESSAGE_CHECKNEWSCANBACKWARDRESULT_H
