// Generated by gencpp from file inspection_realsense/computeGlobalPanoramaActionGoal.msg
// DO NOT EDIT!


#ifndef INSPECTION_REALSENSE_MESSAGE_COMPUTEGLOBALPANORAMAACTIONGOAL_H
#define INSPECTION_REALSENSE_MESSAGE_COMPUTEGLOBALPANORAMAACTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <inspection_realsense/computeGlobalPanoramaGoal.h>

namespace inspection_realsense
{
template <class ContainerAllocator>
struct computeGlobalPanoramaActionGoal_
{
  typedef computeGlobalPanoramaActionGoal_<ContainerAllocator> Type;

  computeGlobalPanoramaActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  computeGlobalPanoramaActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::inspection_realsense::computeGlobalPanoramaGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::inspection_realsense::computeGlobalPanoramaActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::inspection_realsense::computeGlobalPanoramaActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct computeGlobalPanoramaActionGoal_

typedef ::inspection_realsense::computeGlobalPanoramaActionGoal_<std::allocator<void> > computeGlobalPanoramaActionGoal;

typedef boost::shared_ptr< ::inspection_realsense::computeGlobalPanoramaActionGoal > computeGlobalPanoramaActionGoalPtr;
typedef boost::shared_ptr< ::inspection_realsense::computeGlobalPanoramaActionGoal const> computeGlobalPanoramaActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::inspection_realsense::computeGlobalPanoramaActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::inspection_realsense::computeGlobalPanoramaActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace inspection_realsense

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'inspection_realsense': ['/home/irobot/realsense_ws/devel/share/inspection_realsense/msg', '/home/irobot/realsense_ws/src/inspection_realsense/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::inspection_realsense::computeGlobalPanoramaActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::inspection_realsense::computeGlobalPanoramaActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::inspection_realsense::computeGlobalPanoramaActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::inspection_realsense::computeGlobalPanoramaActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::inspection_realsense::computeGlobalPanoramaActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::inspection_realsense::computeGlobalPanoramaActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::inspection_realsense::computeGlobalPanoramaActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "25391e421136bd2856b2ee829477eb6a";
  }

  static const char* value(const ::inspection_realsense::computeGlobalPanoramaActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x25391e421136bd28ULL;
  static const uint64_t static_value2 = 0x56b2ee829477eb6aULL;
};

template<class ContainerAllocator>
struct DataType< ::inspection_realsense::computeGlobalPanoramaActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "inspection_realsense/computeGlobalPanoramaActionGoal";
  }

  static const char* value(const ::inspection_realsense::computeGlobalPanoramaActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::inspection_realsense::computeGlobalPanoramaActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalID goal_id\n\
computeGlobalPanoramaGoal goal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalID\n\
# The stamp should store the time at which this goal was requested.\n\
# It is used by an action server when it tries to preempt all\n\
# goals that were requested before a certain time\n\
time stamp\n\
\n\
# The id provides a way to associate feedback and\n\
# result message with specific goal requests. The id\n\
# specified must be unique.\n\
string id\n\
\n\
\n\
================================================================================\n\
MSG: inspection_realsense/computeGlobalPanoramaGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal definition\n\
std_msgs/String folder_path\n\
std_msgs/String folder_pano_path\n\
std_msgs/String direction\n\
float32 step\n\
float32 long_sheet\n\
float32 width_sheet\n\
\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/String\n\
string data\n\
";
  }

  static const char* value(const ::inspection_realsense::computeGlobalPanoramaActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::inspection_realsense::computeGlobalPanoramaActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct computeGlobalPanoramaActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::inspection_realsense::computeGlobalPanoramaActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::inspection_realsense::computeGlobalPanoramaActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::inspection_realsense::computeGlobalPanoramaGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INSPECTION_REALSENSE_MESSAGE_COMPUTEGLOBALPANORAMAACTIONGOAL_H
