// Generated by gencpp from file inspection_realsense/moveLeftStepGoal.msg
// DO NOT EDIT!


#ifndef INSPECTION_REALSENSE_MESSAGE_MOVELEFTSTEPGOAL_H
#define INSPECTION_REALSENSE_MESSAGE_MOVELEFTSTEPGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace inspection_realsense
{
template <class ContainerAllocator>
struct moveLeftStepGoal_
{
  typedef moveLeftStepGoal_<ContainerAllocator> Type;

  moveLeftStepGoal_()
    : vel(0.0)
    , step(0.0)  {
    }
  moveLeftStepGoal_(const ContainerAllocator& _alloc)
    : vel(0.0)
    , step(0.0)  {
  (void)_alloc;
    }



   typedef float _vel_type;
  _vel_type vel;

   typedef float _step_type;
  _step_type step;





  typedef boost::shared_ptr< ::inspection_realsense::moveLeftStepGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::inspection_realsense::moveLeftStepGoal_<ContainerAllocator> const> ConstPtr;

}; // struct moveLeftStepGoal_

typedef ::inspection_realsense::moveLeftStepGoal_<std::allocator<void> > moveLeftStepGoal;

typedef boost::shared_ptr< ::inspection_realsense::moveLeftStepGoal > moveLeftStepGoalPtr;
typedef boost::shared_ptr< ::inspection_realsense::moveLeftStepGoal const> moveLeftStepGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::inspection_realsense::moveLeftStepGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::inspection_realsense::moveLeftStepGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace inspection_realsense

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'inspection_realsense': ['/home/irobot/realsense_ws/devel/share/inspection_realsense/msg', '/home/irobot/realsense_ws/src/inspection_realsense/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::inspection_realsense::moveLeftStepGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::inspection_realsense::moveLeftStepGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::inspection_realsense::moveLeftStepGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::inspection_realsense::moveLeftStepGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::inspection_realsense::moveLeftStepGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::inspection_realsense::moveLeftStepGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::inspection_realsense::moveLeftStepGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9ada90ea3a4f18220a8f5d7e68a0f457";
  }

  static const char* value(const ::inspection_realsense::moveLeftStepGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9ada90ea3a4f1822ULL;
  static const uint64_t static_value2 = 0x0a8f5d7e68a0f457ULL;
};

template<class ContainerAllocator>
struct DataType< ::inspection_realsense::moveLeftStepGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "inspection_realsense/moveLeftStepGoal";
  }

  static const char* value(const ::inspection_realsense::moveLeftStepGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::inspection_realsense::moveLeftStepGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal definition\n\
float32 vel\n\
float32 step\n\
";
  }

  static const char* value(const ::inspection_realsense::moveLeftStepGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::inspection_realsense::moveLeftStepGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vel);
      stream.next(m.step);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct moveLeftStepGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::inspection_realsense::moveLeftStepGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::inspection_realsense::moveLeftStepGoal_<ContainerAllocator>& v)
  {
    s << indent << "vel: ";
    Printer<float>::stream(s, indent + "  ", v.vel);
    s << indent << "step: ";
    Printer<float>::stream(s, indent + "  ", v.step);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INSPECTION_REALSENSE_MESSAGE_MOVELEFTSTEPGOAL_H
