// Generated by gencpp from file inspection_realsense/moveBackwardGoal.msg
// DO NOT EDIT!


#ifndef INSPECTION_REALSENSE_MESSAGE_MOVEBACKWARDGOAL_H
#define INSPECTION_REALSENSE_MESSAGE_MOVEBACKWARDGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace inspection_realsense
{
template <class ContainerAllocator>
struct moveBackwardGoal_
{
  typedef moveBackwardGoal_<ContainerAllocator> Type;

  moveBackwardGoal_()
    : vel(0.0)
    , n_pasadas_ant(0)
    , n_imgs_ant(0)  {
    }
  moveBackwardGoal_(const ContainerAllocator& _alloc)
    : vel(0.0)
    , n_pasadas_ant(0)
    , n_imgs_ant(0)  {
  (void)_alloc;
    }



   typedef float _vel_type;
  _vel_type vel;

   typedef int32_t _n_pasadas_ant_type;
  _n_pasadas_ant_type n_pasadas_ant;

   typedef int32_t _n_imgs_ant_type;
  _n_imgs_ant_type n_imgs_ant;





  typedef boost::shared_ptr< ::inspection_realsense::moveBackwardGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::inspection_realsense::moveBackwardGoal_<ContainerAllocator> const> ConstPtr;

}; // struct moveBackwardGoal_

typedef ::inspection_realsense::moveBackwardGoal_<std::allocator<void> > moveBackwardGoal;

typedef boost::shared_ptr< ::inspection_realsense::moveBackwardGoal > moveBackwardGoalPtr;
typedef boost::shared_ptr< ::inspection_realsense::moveBackwardGoal const> moveBackwardGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::inspection_realsense::moveBackwardGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::inspection_realsense::moveBackwardGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace inspection_realsense

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'inspection_realsense': ['/home/irobot/nav_insp_ws/devel/share/inspection_realsense/msg', '/home/irobot/nav_insp_ws/src/inspection_realsense/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::inspection_realsense::moveBackwardGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::inspection_realsense::moveBackwardGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::inspection_realsense::moveBackwardGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::inspection_realsense::moveBackwardGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::inspection_realsense::moveBackwardGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::inspection_realsense::moveBackwardGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::inspection_realsense::moveBackwardGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "26095be20a715ca0a2049a176afb9bed";
  }

  static const char* value(const ::inspection_realsense::moveBackwardGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x26095be20a715ca0ULL;
  static const uint64_t static_value2 = 0xa2049a176afb9bedULL;
};

template<class ContainerAllocator>
struct DataType< ::inspection_realsense::moveBackwardGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "inspection_realsense/moveBackwardGoal";
  }

  static const char* value(const ::inspection_realsense::moveBackwardGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::inspection_realsense::moveBackwardGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal definition\n\
float32 vel\n\
int32 n_pasadas_ant\n\
int32 n_imgs_ant\n\
\n\
";
  }

  static const char* value(const ::inspection_realsense::moveBackwardGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::inspection_realsense::moveBackwardGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vel);
      stream.next(m.n_pasadas_ant);
      stream.next(m.n_imgs_ant);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct moveBackwardGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::inspection_realsense::moveBackwardGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::inspection_realsense::moveBackwardGoal_<ContainerAllocator>& v)
  {
    s << indent << "vel: ";
    Printer<float>::stream(s, indent + "  ", v.vel);
    s << indent << "n_pasadas_ant: ";
    Printer<int32_t>::stream(s, indent + "  ", v.n_pasadas_ant);
    s << indent << "n_imgs_ant: ";
    Printer<int32_t>::stream(s, indent + "  ", v.n_imgs_ant);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INSPECTION_REALSENSE_MESSAGE_MOVEBACKWARDGOAL_H
