#goal definition
std_msgs/String folder_path1
int32 n_imgs1
std_msgs/String folder_path2
int32 n_imgs2
---
#result definition
#bool finished
float32 large
float32 width
---
#feedback
#int32[] sequence
float32 large
float32 width
