(cl:in-package irobot_fcpp_simul-srv)
(cl:export '(LOAD_INPUTDATA-VAL
          LOAD_INPUTDATA
          LOAD_POLYGON-VAL
          LOAD_POLYGON
          GET_INPUT_DATA-VAL
          GET_INPUT_DATA
          GET_WORKING_ZONESH-VAL
          GET_WORKING_ZONESH
          GET_WORKING_ZONESC-VAL
          GET_WORKING_ZONESC
          GET_INSPECTION_ZONES-VAL
          GET_INSPECTION_ZONES
          GET_ROT_ZONE-VAL
          GET_ROT_ZONE
          COMPUTE_ADQUIREIMGS-VAL
          COMPUTE_ADQUIREIMGS
          COMPUTE_PANORAMA-VAL
          COMPUTE_PANORAMA
          MERGE_PANORAMAS-VAL
          MERGE_PANORAMAS
          COMPUTE_DETECTPOLYS-VAL
          COMPUTE_DETECTPOLYS
          COMPUTE_FCPP_DEFECT_I-VAL
          COMPUTE_FCPP_DEFECT_I
          COMPUTE_FCPP_ZONE_I-VAL
          COMPUTE_FCPP_ZONE_I
          COMPUTE_FCPP_INSPECTION_ZONE_I-VAL
          COMPUTE_FCPP_INSPECTION_ZONE_I
          EXECUTE_FCPP_DEFECT_I-VAL
          EXECUTE_FCPP_DEFECT_I
          EXECUTE_FCPP_ZONE_I-VAL
          EXECUTE_FCPP_ZONE_I
          CHANGE_DEFECT_REPARATION_GOAL-VAL
          CHANGE_DEFECT_REPARATION_GOAL
          CHANGE_INSPECTION_GOAL-VAL
          CHANGE_INSPECTION_GOAL
          GET_POLY_I-VAL
          GET_POLY_I
          GET_DEFECT_I-VAL
          GET_DEFECT_I
          GET_DEFECT_PATH-VAL
          GET_DEFECT_PATH
          GET_INSPECTION_I-VAL
          GET_INSPECTION_I
          GET_INSPECTION_PATH-VAL
          GET_INSPECTION_PATH
          ACTIVATE_VIZS-VAL
          ACTIVATE_VIZS
          LONG_ROBOTX-VAL
          LONG_ROBOTX
          LONG_ROBOTY-VAL
          LONG_ROBOTY
          LONG_HERRX-VAL
          LONG_HERRX
          LONG_HERRY-VAL
          LONG_HERRY
          TRAS_HERRX-VAL
          TRAS_HERRX
          TRAS_HERRY-VAL
          TRAS_HERRY
          LONG_CAMX-VAL
          LONG_CAMX
          LONG_CAMY-VAL
          LONG_CAMY
          TRAS_CAMX-VAL
          TRAS_CAMX
          TRAS_CAMY-VAL
          TRAS_CAMY
          LONG_AREAX-VAL
          LONG_AREAX
          LONG_AREAY-VAL
          LONG_AREAY
          INPUT_POLY-VAL
          INPUT_POLY
          ID_POLY-VAL
          ID_POLY
          ID_DEFECTO-VAL
          ID_DEFECTO
          ID_ZONA-VAL
          ID_ZONA
          LONG_ROBOTX-VAL
          LONG_ROBOTX
          LONG_ROBOTY-VAL
          LONG_ROBOTY
          LONG_HERRX-VAL
          LONG_HERRX
          LONG_HERRY-VAL
          LONG_HERRY
          TRAS_HERRX-VAL
          TRAS_HERRX
          TRAS_HERRY-VAL
          TRAS_HERRY
          LONG_CAMX-VAL
          LONG_CAMX
          LONG_CAMY-VAL
          LONG_CAMY
          TRAS_CAMX-VAL
          TRAS_CAMX
          TRAS_CAMY-VAL
          TRAS_CAMY
          LONG_AREAX-VAL
          LONG_AREAX
          LONG_AREAY-VAL
          LONG_AREAY
          ZONEH0-VAL
          ZONEH0
          ZONEH90-VAL
          ZONEH90
          ZONEH180-VAL
          ZONEH180
          ZONEH270-VAL
          ZONEH270
          ZONEC0-VAL
          ZONEC0
          ZONEC90-VAL
          ZONEC90
          ZONEC180-VAL
          ZONEC180
          ZONEC270-VAL
          ZONEC270
          PATH_TRAY0-VAL
          PATH_TRAY0
          PATH_TRAY90-VAL
          PATH_TRAY90
          PATH_TRAY180-VAL
          PATH_TRAY180
          PATH_TRAY270-VAL
          PATH_TRAY270
          ZONE_ROT-VAL
          ZONE_ROT
          DEFECTO_I-VAL
          DEFECTO_I
          POLY_I-VAL
          POLY_I
          N_DEFECTOS-VAL
          N_DEFECTOS
          DEFECT_I_PATHS-VAL
          DEFECT_I_PATHS
          INSPECTION_I_PATHS-VAL
          INSPECTION_I_PATHS
))