// Generated by gencpp from file irobot_dimensions_pckg/findCornersResult.msg
// DO NOT EDIT!


#ifndef IROBOT_DIMENSIONS_PCKG_MESSAGE_FINDCORNERSRESULT_H
#define IROBOT_DIMENSIONS_PCKG_MESSAGE_FINDCORNERSRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace irobot_dimensions_pckg
{
template <class ContainerAllocator>
struct findCornersResult_
{
  typedef findCornersResult_<ContainerAllocator> Type;

  findCornersResult_()
    : finished(false)
    , n_imgs1(0)
    , n_imgs2(0)  {
    }
  findCornersResult_(const ContainerAllocator& _alloc)
    : finished(false)
    , n_imgs1(0)
    , n_imgs2(0)  {
  (void)_alloc;
    }



   typedef uint8_t _finished_type;
  _finished_type finished;

   typedef int32_t _n_imgs1_type;
  _n_imgs1_type n_imgs1;

   typedef int32_t _n_imgs2_type;
  _n_imgs2_type n_imgs2;





  typedef boost::shared_ptr< ::irobot_dimensions_pckg::findCornersResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::irobot_dimensions_pckg::findCornersResult_<ContainerAllocator> const> ConstPtr;

}; // struct findCornersResult_

typedef ::irobot_dimensions_pckg::findCornersResult_<std::allocator<void> > findCornersResult;

typedef boost::shared_ptr< ::irobot_dimensions_pckg::findCornersResult > findCornersResultPtr;
typedef boost::shared_ptr< ::irobot_dimensions_pckg::findCornersResult const> findCornersResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::irobot_dimensions_pckg::findCornersResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::irobot_dimensions_pckg::findCornersResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace irobot_dimensions_pckg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'irobot_dimensions_pckg': ['/home/irobot/catkin_ws/src/irobot_dimensions_pckg/msg', '/home/irobot/catkin_ws/devel/share/irobot_dimensions_pckg/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg', '/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::irobot_dimensions_pckg::findCornersResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::irobot_dimensions_pckg::findCornersResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::irobot_dimensions_pckg::findCornersResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::irobot_dimensions_pckg::findCornersResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::irobot_dimensions_pckg::findCornersResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::irobot_dimensions_pckg::findCornersResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::irobot_dimensions_pckg::findCornersResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "887012e06d10bcb9605b129d45f0aa9a";
  }

  static const char* value(const ::irobot_dimensions_pckg::findCornersResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x887012e06d10bcb9ULL;
  static const uint64_t static_value2 = 0x605b129d45f0aa9aULL;
};

template<class ContainerAllocator>
struct DataType< ::irobot_dimensions_pckg::findCornersResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "irobot_dimensions_pckg/findCornersResult";
  }

  static const char* value(const ::irobot_dimensions_pckg::findCornersResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::irobot_dimensions_pckg::findCornersResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#result definition\n\
bool finished\n\
int32 n_imgs1\n\
int32 n_imgs2\n\
";
  }

  static const char* value(const ::irobot_dimensions_pckg::findCornersResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::irobot_dimensions_pckg::findCornersResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.finished);
      stream.next(m.n_imgs1);
      stream.next(m.n_imgs2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct findCornersResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::irobot_dimensions_pckg::findCornersResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::irobot_dimensions_pckg::findCornersResult_<ContainerAllocator>& v)
  {
    s << indent << "finished: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.finished);
    s << indent << "n_imgs1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.n_imgs1);
    s << indent << "n_imgs2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.n_imgs2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IROBOT_DIMENSIONS_PCKG_MESSAGE_FINDCORNERSRESULT_H
