// Generated by gencpp from file irobot_dimensions_pckg/obtainDimensionGoal.msg
// DO NOT EDIT!


#ifndef IROBOT_DIMENSIONS_PCKG_MESSAGE_OBTAINDIMENSIONGOAL_H
#define IROBOT_DIMENSIONS_PCKG_MESSAGE_OBTAINDIMENSIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/String.h>
#include <std_msgs/String.h>

namespace irobot_dimensions_pckg
{
template <class ContainerAllocator>
struct obtainDimensionGoal_
{
  typedef obtainDimensionGoal_<ContainerAllocator> Type;

  obtainDimensionGoal_()
    : folder_path1()
    , n_imgs1(0)
    , folder_path2()
    , n_imgs2(0)  {
    }
  obtainDimensionGoal_(const ContainerAllocator& _alloc)
    : folder_path1(_alloc)
    , n_imgs1(0)
    , folder_path2(_alloc)
    , n_imgs2(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::String_<ContainerAllocator>  _folder_path1_type;
  _folder_path1_type folder_path1;

   typedef int32_t _n_imgs1_type;
  _n_imgs1_type n_imgs1;

   typedef  ::std_msgs::String_<ContainerAllocator>  _folder_path2_type;
  _folder_path2_type folder_path2;

   typedef int32_t _n_imgs2_type;
  _n_imgs2_type n_imgs2;





  typedef boost::shared_ptr< ::irobot_dimensions_pckg::obtainDimensionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::irobot_dimensions_pckg::obtainDimensionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct obtainDimensionGoal_

typedef ::irobot_dimensions_pckg::obtainDimensionGoal_<std::allocator<void> > obtainDimensionGoal;

typedef boost::shared_ptr< ::irobot_dimensions_pckg::obtainDimensionGoal > obtainDimensionGoalPtr;
typedef boost::shared_ptr< ::irobot_dimensions_pckg::obtainDimensionGoal const> obtainDimensionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::irobot_dimensions_pckg::obtainDimensionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::irobot_dimensions_pckg::obtainDimensionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace irobot_dimensions_pckg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'irobot_dimensions_pckg': ['/home/irobot/catkin_ws/src/irobot_dimensions_pckg/msg', '/home/irobot/catkin_ws/devel/share/irobot_dimensions_pckg/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg', '/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::irobot_dimensions_pckg::obtainDimensionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::irobot_dimensions_pckg::obtainDimensionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::irobot_dimensions_pckg::obtainDimensionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::irobot_dimensions_pckg::obtainDimensionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::irobot_dimensions_pckg::obtainDimensionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::irobot_dimensions_pckg::obtainDimensionGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::irobot_dimensions_pckg::obtainDimensionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d5a4c79a4840d0e4c90009d8806c0768";
  }

  static const char* value(const ::irobot_dimensions_pckg::obtainDimensionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd5a4c79a4840d0e4ULL;
  static const uint64_t static_value2 = 0xc90009d8806c0768ULL;
};

template<class ContainerAllocator>
struct DataType< ::irobot_dimensions_pckg::obtainDimensionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "irobot_dimensions_pckg/obtainDimensionGoal";
  }

  static const char* value(const ::irobot_dimensions_pckg::obtainDimensionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::irobot_dimensions_pckg::obtainDimensionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal definition\n\
std_msgs/String folder_path1\n\
int32 n_imgs1\n\
std_msgs/String folder_path2\n\
int32 n_imgs2\n\
\n\
================================================================================\n\
MSG: std_msgs/String\n\
string data\n\
";
  }

  static const char* value(const ::irobot_dimensions_pckg::obtainDimensionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::irobot_dimensions_pckg::obtainDimensionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.folder_path1);
      stream.next(m.n_imgs1);
      stream.next(m.folder_path2);
      stream.next(m.n_imgs2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct obtainDimensionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::irobot_dimensions_pckg::obtainDimensionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::irobot_dimensions_pckg::obtainDimensionGoal_<ContainerAllocator>& v)
  {
    s << indent << "folder_path1: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.folder_path1);
    s << indent << "n_imgs1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.n_imgs1);
    s << indent << "folder_path2: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.folder_path2);
    s << indent << "n_imgs2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.n_imgs2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IROBOT_DIMENSIONS_PCKG_MESSAGE_OBTAINDIMENSIONGOAL_H
