# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from irobot_inspection_pckg/getCompletePanoramaGoal.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class getCompletePanoramaGoal(genpy.Message):
  _md5sum = "2465211dc6ab145b5fd1fa5a332f2607"
  _type = "irobot_inspection_pckg/getCompletePanoramaGoal"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
#goal definition
std_msgs/String folder_pano_path
int32 images_number
std_msgs/String name_0
std_msgs/String name_180


================================================================================
MSG: std_msgs/String
string data
"""
  __slots__ = ['folder_pano_path','images_number','name_0','name_180']
  _slot_types = ['std_msgs/String','int32','std_msgs/String','std_msgs/String']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       folder_pano_path,images_number,name_0,name_180

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(getCompletePanoramaGoal, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.folder_pano_path is None:
        self.folder_pano_path = std_msgs.msg.String()
      if self.images_number is None:
        self.images_number = 0
      if self.name_0 is None:
        self.name_0 = std_msgs.msg.String()
      if self.name_180 is None:
        self.name_180 = std_msgs.msg.String()
    else:
      self.folder_pano_path = std_msgs.msg.String()
      self.images_number = 0
      self.name_0 = std_msgs.msg.String()
      self.name_180 = std_msgs.msg.String()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.folder_pano_path.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.images_number
      buff.write(_get_struct_i().pack(_x))
      _x = self.name_0.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.name_180.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.folder_pano_path is None:
        self.folder_pano_path = std_msgs.msg.String()
      if self.name_0 is None:
        self.name_0 = std_msgs.msg.String()
      if self.name_180 is None:
        self.name_180 = std_msgs.msg.String()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.folder_pano_path.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.folder_pano_path.data = str[start:end]
      start = end
      end += 4
      (self.images_number,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.name_0.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.name_0.data = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.name_180.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.name_180.data = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.folder_pano_path.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.images_number
      buff.write(_get_struct_i().pack(_x))
      _x = self.name_0.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.name_180.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.folder_pano_path is None:
        self.folder_pano_path = std_msgs.msg.String()
      if self.name_0 is None:
        self.name_0 = std_msgs.msg.String()
      if self.name_180 is None:
        self.name_180 = std_msgs.msg.String()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.folder_pano_path.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.folder_pano_path.data = str[start:end]
      start = end
      end += 4
      (self.images_number,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.name_0.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.name_0.data = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.name_180.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.name_180.data = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_i = None
def _get_struct_i():
    global _struct_i
    if _struct_i is None:
        _struct_i = struct.Struct("<i")
    return _struct_i
